services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  energyforecastingapi:
    build:
      context: .
      dockerfile: EnergyForecastingAPI/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__MongoDb: "mongodb://root:rootpassword@mongodb:27017"

volumes:
  mongodb_data:
